#!/bin/bash

# Prompt password early on. Also ensures user really wants to uninstall.
sudo echo > /dev/null 2>&1

# If arguments count is not 1 or argument is not 'uninstall' exit.
if [[ $# != 1 || "$1" != "uninstall" ]]; then exit; fi

# Only continue with uninstall if nodecliac was installed for 'aconly'.
if [[ -z "$(grep -o "aconly" "$HOME/.nodecliac/.setup.db.json")" ]]; then exit; fi

# Remove nodecliac from ~/.bashrc.
if [[ -n "$(grep -o "ncliac=~/.nodecliac/src/main.sh" ~/.bashrc)" ]]; then
	# [https://stackoverflow.com/a/57813295]
	perl -0pi -e 's/ncliac=~\/.nodecliac\/src\/main.sh;if \[ -f "\$ncliac" \];then source "\$ncliac";fi;//;s/\n+(\n)$/\1/gs' ~/.bashrc
	# perl -pi -e "s/ncliac=~\/.nodecliac\/src\/main.sh;if \[ -f \"\\\$ncliac\" \];then source \"\\\$ncliac\";fi;// if /^ncliac/" ~/.bashrc
fi

# Delete main folder.
if [[ -e ~/.nodecliac ]]; then rm -rf ~/.nodecliac; fi

# Remove bin file.
if [[ -e /usr/local/bin/nodecliac ]]; then sudo rm -f /usr/local/bin/nodecliac; fi
